site_name: java-linda
site_url: https://lindaprotocol.github.io/documentation-en/
repo_url: https://github.com/lindaprotocol/documentation-en

nav:
    - Home: index.md
    - Getting Started With java-linda:
        - Getting Started: getting_started/getting_started_with_javalinda.md
    - Using java-linda:
        - Deploying: using_javalinda/installing_javalinda.md
        - Backup and Restore: using_javalinda/backup_restore.md
        - Lite FullNode: using_javalinda/litefullnode.md
        - Private Network: using_javalinda/private_network.md
        - Event Subscription: architecture/event.md
        - Database Configuration: architecture/database.md
        - Network Connection: using_javalinda/connecting_to_linda.md
        - Node Monitoring: using_javalinda/metrics.md
        - Node Maintenance Tool: using_javalinda/toolkit.md
    - API:
        - HTTP API: api/http.md
        - gRPC API: api/rpc.md
        - jsonRPC API: api/json-rpc.md
    - Core Protocol:
        - DPoS: mechanism-algorithm/dpos.md
        - Super Representative: mechanism-algorithm/sr.md
        - Account Model: mechanism-algorithm/account.md
        - Resource Model: mechanism-algorithm/resource.md
        - Smart Contract: contracts/contract.md
        - System Contract: mechanism-algorithm/system-contracts.md
        - Decentralized Exchange: mechanism-algorithm/dex.md
        - Account Permission Management: mechanism-algorithm/multi-signatures.md
    - For java-linda Developers:
        - Developer Guide: developers/java-linda.md
        - TIPs Workflow: developers/tips.md
        - Issue Workflow: developers/issue-workflow.md
        - Governance Workflow: developers/governance.md
        - Configure the IDE: developers/run-in-idea.md
        - Development Example: developers/demo.md
        - Core Modules: developers/code-structure.md
    - For Dapp Developers:
        - Tools: contracts/tools.md
    - Clients:
        - wallet-cli: clients/wallet-cli.md
    - Releases:
        - Deployment Manual for the New Version: releases/upgrade-instruction.md
        - Integrity Check: releases/signature_verification.md
        - History: releases/history.md
    - Appendix:
        - Glossary: glossary.md

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.sections  # Enable grouping in the left navigation bar
    - navigation.footer
    - toc.integrate
    - search.highlight  # Highlight matching content during search
    - search.suggest  # Show suggestions during search
    - content.code.annotate  # Code block annotations
    - content.tooltips  # Tooltips in content
  palette:
    primary: custom  # Primary color
    accent: custom  # Accent color
  font:
    text: Roboto  # Body text font
    code: Roboto Mono  # Code font

extra_javascript:
    - javascripts/toc.js
    - javascripts/nav-toc.js
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - admonition
    - footnotes
    - codehilite
    - toc:
        permalink: true
        toc_depth: 3
    - pymdownx.arithmatex
    - pymdownx.tilde
    - pymdownx.tasklist
    - pymdownx.superfences

plugins:
  - search
  - exclude:
      glob:
        - clients/linda-grid.md
        - contracts/lrc20.md
        - contracts/lvm.md
        - developers/contribution.md
        - developers/gpg.md
        - developers/incentives.md
        - developers/resources.md
        - faq/index.md
        - introduction/index.md
        - introduction/overview.md
        - mechanism-algorithm/shielded-LRC20-contract.md
        - mechanism-algorithm/lrc10.md

